# Constants used in the game

# Camera
CAMERA_WIDTH = 400
CAMERA_HEIGHT = 600

# Objects
PLATFORM_HEIGHT = 10
PLATFORM_WIDTH = 60
VERTICAL_DIST_BTW_PLATFORMS = 100
PLATFORM_COUNT = 6
Y_BASELINE = CAMERA_HEIGHT - 50

SPRITESHEET_PATH = "SpriteSheet.png"
SPRITESHEET_ROW_COUNT = 1
SPRITESHEET_COLUMN_COUNT = 11

# Physics
PLAYER_X_SPEED_INCREMENT = 3
FRICTION = 0.8
GRAVITY = 0.5
REBOUNCE_SPEED = -15

# Misc
FRAME_PER_MOVEMENT = 30
HIGHSCORE_PATH = "highscore.txt"